services:
  - type: web
    name: yurayurastudio
    runtime: node
    buildCommand: ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: yurayurastudio-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET
        sync: false

databases:
  - name: yurayurastudio-db
    plan: free
    databaseName: yurayurastudio
    user: yurayurastudio_user